services:
  web-server:
    container_name: web-server
    build:
      context: build.dev/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./build.dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - project-name-network
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    # TODO: estudar healthcheck e rodar tests antes
    container_name: php-fpm
    build:
      context: build.dev/php-fpm
      dockerfile: Dockerfile
    user: 1000:1000
    restart: always
    volumes:
      - .:/var/www
    networks:
      - project-name-network

networks:
  project-name-network:
    driver: bridge
