services:
  server:
    container_name: nginx_server
    image: nginx:1.28.0
    volumes:
      - build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - build/nginx/site.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8080:80
    depends_on:
        php-fpm
    php-fpm:
      build:
        context: build/php-fpm
        dockerfile: Dockerfile
    volumes:
      - build/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - build/php-fpm/php.ini-production:/usr/local/etc/php/php.ini-production
