services:
  web-server:
    container_name: web-server_prod
    build:
      context: ./../..
      dockerfile: docker/production/nginx/Dockerfile
    restart: on-failure
    volumes:
      - ./../../logs/nginx:/var/www/logs/nginx
    networks:
      - project-name-network
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    # TODO: estudar healthcheck e rodar tests
    container_name: php-fpm_prod
    build:
      context: ./../..
      dockerfile: docker/production/php-fpm/Dockerfile
    restart: on-failure
    volumes:
      - ./../../logs/php-fpm:/var/www/logs/php-fpm
    networks:
      - project-name-network

networks:
  project-name-network:
    driver: bridge
